name: Publish
on:
  push:
    branches:
      - "main"

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Asciidoctor
        run: gem install asciidoctor asciidoctor-epub3

      - name: Generate html from AsciiDoc
        run: |
          asciidoctor livro.adoc -o index.html

      - name: Generate EPUB from AsciiDoc
        run: |
          asciidoctor-epub3 livro.adoc -o 'Python Fluente, Segunda Edição (2023).epub'

      - name: Install asciidoctor-chunker
        run: npm install -g asciidoctor-chunker

      - name: Split html
        run: |
          asciidoctor-chunker index.html -o output
          tar -zcvf livro.tar.gz output

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            index.html
            livro.tar.gz
            'Python Fluente, Segunda Edição (2023).epub'